---
- name: Deploy infra stack Apache, Nodejs runtime and App
  hosts: web
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest

  - name: install apache proxy definition
    copy:
      src: nodeproxy.conf
      dest: /etc/httpd/conf.d/nodeproxy.conf
    notify: apache-reload

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: install nodejs
    dnf:
      name: 'nodejs'
      state: present

  - name: install nodejs systemd unit file
    copy:
      src: node.service
      dest: /etc/systemd/system/node.service
    notify: systemd-reload

  handlers:
  - name: systemd-reload
    systemd:
      daemon_reload: yes

  - name: apache-reload
    systemd:
      name: httpd
      state: reloaded
